%%{init: { 'logLevel': 'debug', 'theme': 'forest', 'fontSize':'40px', 'timeline': {'disableMulticolor': true}}}%%

timeline
    section Early DevOps
        Beginning of DevOps as "Agile Infrastructure": 2007
    section Automation Era
        Start of Automation Era: 2010
    section Ansible Development
        Ansible, Inc. Founded: 2012
        
    section Acquisitions & Developments
        Red Hat Acquires Ansible, Inc.: 2015
        Ansible Tower Development: 2015
    section Platform Evolution
        Launch of AWX: 2017
        Launch of Ansible Automation Platform: 2019    
